### ISSUE TITLE
Incompatible shapes in MPC stage

### ISSUE THREAD

**Issue by iou2much** [athena-team/athena#102]
Hi, when I try to use my own data to train MPC model, it got following error after 200 step. Is it due to my data ?
![image](https://user-images.githubusercontent.com/2812471/78455568-b713ec00-76d1-11ea-8bbc-7004cddf7908.png)

**Comment by Some-random** [comment]
The length of your input exceeded the max length of encoder positional embedding. Try changing **max_position** in PositionalEncoding to a bigger a value or use **input_length_range** in config json to limit the max length of your input.

**Comment by iou2much** [comment]
Thank you, @Some-random . It works.
Could you please give some advice about this parameter? 
Is it harder to reach the best performance if max_position is larger, i.e. use longer duration audio?
Our data are mostly about 60 seconds.

**Comment by Some-random** [comment]
> Thank you, @Some-random . It works.
> Could you please give some advice about this parameter?
> Is it harder to reach the best performance if max_position is larger, i.e. use longer duration audio?
> Our data are mostly about 60 seconds.

Using audios as long as 60 secs isn't recommended because it will take too much GPU memory. In  your case, splitting audio into smaller chunks using VAD first would be a better choice.

**Comment by iou2much** [comment]
I see. Thank you
