### ISSUE TITLE
call() got an unexpected keyword argument 'training'

### ISSUE THREAD

**Issue by studyself** [athena-team/athena#103]
384 [1,0]<stderr>:WARNING:tensorflow:Entity <bound method TensorFlowOpLayer._defun_call of <tensorflow.python.eager.function.TfMethodTarget object at 0x7fda720b4b70>> could not be transformed and will be ex    ecuted as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound meth    od TensorFlowOpLayer._defun_call of <tensorflow.python.eager.function.TfMethodTarget object at 0x7fda720b4b70>>: AssertionError: Bad argument number for Name: 3, expecting 4
385 [1,0]<stderr>:2020-04-05 01:25:48.780970: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
386 [1,1]<stderr>:WARNING:tensorflow:Entity <bound method TensorFlowOpLayer._defun_call of <tensorflow.python.eager.function.TfMethodTarget object at 0x7f28792be7f0>> could not be transformed and will be ex    ecuted as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound meth    od TensorFlowOpLayer._defun_call of <tensorflow.python.eager.function.TfMethodTarget object at 0x7f28792be7f0>>: AssertionError: Bad argument number for Name: 3, expecting 4
387 [1,1]<stderr>:WARNING:tensorflow:Entity <bound method TensorFlowOpLayer._defun_call of <tensorflow.python.eager.function.TfMethodTarget object at 0x7f28792be7f0>> could not be transformed and will be ex    ecuted as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound meth    od TensorFlowOpLayer._defun_call of <tensorflow.python.eager.function.TfMethodTarget object at 0x7f28792be7f0>>: AssertionError: Bad argument number for Name: 3, expecting 4
388 [1,1]<stderr>:2020-04-05 01:25:48.903736: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
389 [1,1]<stderr>:Traceback (most recent call last):
390 [1,1]<stderr>:  File "athena/horovod_main.py", line 42, in <module>
391 [1,1]<stderr>:    train(json_file, HorovodSolver, hvd.size(), hvd.rank())
392 [1,1]<stderr>:  File "/qssd/athena/athena/main.py", line 117, in train
393 [1,1]<stderr>:    p, model, optimizer, checkpointer = build_model_from_jsonfile(jsonfile)
394 [1,1]<stderr>:  File "/qssd/athena/athena/main.py", line 105, in build_model_from_jsonfile
395 [1,1]<stderr>:    solver.evaluate_step(model.prepare_samples(iter(dataset).next()))
396 [1,1]<stderr>:  File "/qssd/athena/athena/solver.py", line 96, in evaluate_step
397 [1,1]<stderr>:    logits = self.model(samples, training=False)
398 [1,1]<stderr>:  File "/home/quinnqiu/foundation/Q_athena/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 712, in __call__
399 [1,1]<stderr>:    outputs = self.call(inputs, *args, **kwargs)
400 [1,1]<stderr>:  File "/qssd/athena/athena/models/mtl_seq2seq.py", line 69, in call
401 [1,1]<stderr>:    self.ctc_logits = self.decoder(encoder_output, training=training)
402 [1,1]<stderr>:  File "/home/quinnqiu/foundation/Q_athena/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 712, in __call__
403 [1,1]<stderr>:    outputs = self.call(inputs, *args, **kwargs)
404 [1,1]<stderr>:TypeError: call() got an unexpected keyword argument 'training'
405 [1,0]<stderr>:Traceback (most recent call last):
406 [1,0]<stderr>:  File "athena/horovod_main.py", line 42, in <module>
407 [1,0]<stderr>:    train(json_file, HorovodSolver, hvd.size(), hvd.rank())
408 [1,0]<stderr>:  File "/qssd/athena/athena/main.py", line 117, in train
409 [1,0]<stderr>:    p, model, optimizer, checkpointer = build_model_from_jsonfile(jsonfile)
410 [1,0]<stderr>:  File "/qssd/athena/athena/main.py", line 105, in build_model_from_jsonfile
411 [1,0]<stderr>:    solver.evaluate_step(model.prepare_samples(iter(dataset).next()))
412 [1,0]<stderr>:  File "/qssd/athena/athena/solver.py", line 96, in evaluate_step
413 [1,0]<stderr>:    logits = self.model(samples, training=False)
414 [1,0]<stderr>:  File "/home/quinnqiu/foundation/Q_athena/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 712, in __call__
415 [1,0]<stderr>:    outputs = self.call(inputs, *args, **kwargs)
416 [1,0]<stderr>:  File "/qssd/athena/athena/models/mtl_seq2seq.py", line 69, in call
417 [1,0]<stderr>:    self.ctc_logits = self.decoder(encoder_output, training=training)
418 [1,0]<stderr>:  File "/home/quinnqiu/foundation/Q_athena/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 712, in __call__                                                 
419 [1,0]<stderr>:    outputs = self.call(inputs, *args, **kwargs)
420 [1,0]<stderr>:TypeError: call() got an unexpected keyword argument 'training'
-----------------------
installation is complete, and well done.
tensorflow 2.0.0b0
CUDA 10.0.0

**Comment by studyself** [comment]
[nohup.20200404-6.log](https://github.com/athena-team/athena/files/4432127/nohup.20200404-6.log)
see the log file attached.

**Comment by Some-random** [comment]
This looks like an issue with TF version. Try upgrading your tensorflow version to 2.0.1 or 2.1.0 and let me know if the problem still exists.

**Comment by studyself** [comment]
upgrading fix it.
Thanks.

Bob_JIANG <notifications@github.com> 于2020年4月5日周日 下午12:42写道：

**Comment by tjadamlee** [comment]
I may close this issue, it seems like this issue has been fixed
