### ISSUE TITLE
athena/examples/asr/aishell_sub/run.sh getting config from aishell

### ISSUE THREAD

**Issue by enchyisle** [athena-team/athena#107]
For example:

    python athena/cmvn_main.py \
        examples/asr/aishell/configs/mpc.json examples/asr/aishell/data/all.csv || exit 1

Shouldn't it read/write stuff from aishell_sub?

**Comment by Mitomzhou** [comment]
Yeah, it a bug.  aishell_sub is to solve the problem that a single GPU does not need to install horovod. but u can move run.sh(aishell_sub) to the aishell to run, and then delete aishell_sub.
