### ISSUE TITLE
CMVN values gets very large, and the loss of MPC is NaN

### ISSUE THREAD

**Issue by iou2much** [athena-team/athena#109]
Hi, after I use our own data(10000h) to calculate the cmvn, I find the var is quite large. and the loss of MPC stage is NaN at the very beginning. Do anyone have any idea?

speaker	mean	var
global	[41.53281, 50.375763, 53.979485, 55.0042, 55.01829, 55.294025, 55.537567, 55.66456, 55.297874, 54.5779, 54.301113, 54.04989, 53.69498, 53.33427, 53.045273, 52.622414, 52.82048, 53.421753, 53.865902, 53.84243, 53.45809, 52.944252, 53.01819, 53.3373, 53.863102, 54.33686, 54.909252, 55.299534, 55.040947, 54.846294, 54.568024, 53.713165, 52.363804, 49.36468, 45.567574, 45.262226, 44.527786, 45.601566, 45.84235, 45.581955]	[-1176.7283, -1758.992, -2028.2766, -2111.5051, -2113.496, -2133.8308, -2152.609, -2164.494, -2136.68, -2079.5215, -2057.8743, -2038.9774, -2011.5557, -1983.8772, -1962.4875, -1930.8735, -1947.2842, -1993.6705, -2028.1543, -2025.6558, -1996.1725, -1956.0061, -1962.5137, -1986.1327, -2026.9241, -2065.188, -2109.8545, -2142.8325, -2122.1377, -2107.376, -2086.5679, -2019.9905, -1916.543, -1694.3958, -1440.5925, -1426.0725, -1364.4426, -1428.7397, -1445.1039, -1433.9104]

**Comment by Some-random** [comment]
Variance shouldn't have negative values. It seems like there is something wrong with your cmvn calculation.

**Comment by tjadamlee** [comment]
@Some-random we may have to check that whether there is a bug about global cmvn calculation when the a very lage corpus is used.

**Comment by iou2much** [comment]
Thanks for looking into this. 

My data might be quite variant, thousands of speakers and also may have some garbage clips, like noise, music, etc.
Does it matter? @Some-random @tjadamlee

**Comment by iou2much** [comment]
I just did some experiments.

**1.  when I use all the data (3849540 clips) to compute CMVN. It gets:**

```csv
speaker	mean	var
global	[-11.458747, -13.8062935, -14.773056, -15.058443, -15.055878, -15.142236, -15.2384815, -15.2861395, -15.184855, -15.004456, -14.937626, -14.862481, -14.766846, -14.678121, -14.621394, -14.522068, -14.590279, -14.731953, -14.827337, -14.77892, -14.65017, -14.49369, -14.509164, -14.575226, -14.679297, -14.790304, -14.86249, -14.972713, -14.940675, -14.870071, -14.79416, -14.544769, -14.182741, -13.140521, -11.970985, -12.876977, -14.120078, -14.577636, -14.64444, -14.525528]	[-280.6593, -400.06744, -456.04242, -472.59595, -472.3454, -478.1026, -484.19186, -486.7177, -480.17728, -469.20465, -465.0266, -460.30536, -454.53674, -449.18243, -445.5854, -439.60013, -443.33374, -451.57977, -457.39404, -454.71692, -447.2111, -438.2603, -439.0922, -443.34695, -449.53284, -455.8111, -460.30267, -466.2685, -464.1563, -459.68848, -454.3324, -438.9354, -417.54044, -360.04794, -297.62695, -343.6109, -412.1402, -438.67426, -442.87378, -435.97638]
```
**2. when I use the first million of the clips to compute CMVN. It gets:**
```csv
speaker	mean	var
global	[10.923486, 13.010109, 13.946908, 14.230672, 14.167128, 14.240647, 14.386175, 14.429521, 14.303909, 14.123624, 14.083034, 14.031579, 13.956195, 13.900444, 13.882854, 13.816274, 13.897039, 14.038237, 14.123035, 14.080614, 14.000735, 13.916052, 13.97697, 14.074111, 14.178347, 14.262689, 14.329531, 14.415445, 14.397397, 14.345988, 14.265724, 14.090331, 13.844893, 13.173514, 12.422558, 13.008711, 13.816429, 14.124628, 14.125309, 13.817903]	[20.91298, 24.343964, 26.700623, 26.866516, 26.681625, 27.516144, 28.236954, 27.982681, 27.335419, 26.74852, 26.208313, 25.689331, 25.31456, 24.932999, 24.59488, 24.283478, 24.115417, 24.166458, 24.373703, 24.386597, 24.20082, 24.107178, 24.081741, 24.413437, 24.660263, 24.615341, 24.797943, 24.482834, 24.36473, 24.150818, 23.536407, 22.838028, 22.168549, 21.571976, 19.719315, 19.954208, 20.986832, 21.454498, 21.57872, 21.01178]
```
**3. when I use the latter 2849540 clips to compute CMVN. It gets:**
```csv
speaker	mean	var
global	[10.706122, 12.945589, 13.843145, 14.105223, 14.120722, 14.203944, 14.277449, 14.322074, 14.235685, 14.069682, 14.00042, 13.92407, 13.829724, 13.73798, 13.673741, 13.572355, 13.631356, 13.762076, 13.852783, 13.806102, 13.672217, 13.506154, 13.506403, 13.557284, 13.652725, 13.762564, 13.830316, 13.939399, 13.906135, 13.835582, 13.766824, 13.514759, 13.146294, 12.073899, 10.869639, 11.802343, 13.080408, 13.547596, 13.629309, 13.576775]	[25.609474, 29.985321, 32.22003, 32.230743, 32.167343, 32.777786, 33.076553, 32.794342, 32.309784, 31.979416, 31.775513, 31.46672, 31.243546, 31.00354, 30.644836, 30.279953, 30.18895, 30.408676, 30.774078, 30.894089, 30.7453, 30.623108, 30.571, 31.106644, 31.374847, 31.314392, 31.676956, 31.279175, 31.005249, 30.59291, 29.569138, 28.275925, 26.933304, 24.142456, 17.697388, 20.731049, 24.888977, 26.118454, 26.608932, 26.611694]
```

In summary, the total counts of clips is 3849540, it gots negative number. Yet the either partial subset seems.
I suspect it might be numeric overflow somewhere?
@tjadamlee @Some-random

**Comment by Some-random** [comment]
> I just did some experiments.
> 
> **1. when I use all the data (3849540 clips) to compute CMVN. It gets:**
> 
> ```
> speaker	mean	var
> global	[-11.458747, -13.8062935, -14.773056, -15.058443, -15.055878, -15.142236, -15.2384815, -15.2861395, -15.184855, -15.004456, -14.937626, -14.862481, -14.766846, -14.678121, -14.621394, -14.522068, -14.590279, -14.731953, -14.827337, -14.77892, -14.65017, -14.49369, -14.509164, -14.575226, -14.679297, -14.790304, -14.86249, -14.972713, -14.940675, -14.870071, -14.79416, -14.544769, -14.182741, -13.140521, -11.970985, -12.876977, -14.120078, -14.577636, -14.64444, -14.525528]	[-280.6593, -400.06744, -456.04242, -472.59595, -472.3454, -478.1026, -484.19186, -486.7177, -480.17728, -469.20465, -465.0266, -460.30536, -454.53674, -449.18243, -445.5854, -439.60013, -443.33374, -451.57977, -457.39404, -454.71692, -447.2111, -438.2603, -439.0922, -443.34695, -449.53284, -455.8111, -460.30267, -466.2685, -464.1563, -459.68848, -454.3324, -438.9354, -417.54044, -360.04794, -297.62695, -343.6109, -412.1402, -438.67426, -442.87378, -435.97638]
> ```
> 
> **2. when I use the first million of the clips to compute CMVN. It gets:**
> 
> ```
> speaker	mean	var
> global	[10.923486, 13.010109, 13.946908, 14.230672, 14.167128, 14.240647, 14.386175, 14.429521, 14.303909, 14.123624, 14.083034, 14.031579, 13.956195, 13.900444, 13.882854, 13.816274, 13.897039, 14.038237, 14.123035, 14.080614, 14.000735, 13.916052, 13.97697, 14.074111, 14.178347, 14.262689, 14.329531, 14.415445, 14.397397, 14.345988, 14.265724, 14.090331, 13.844893, 13.173514, 12.422558, 13.008711, 13.816429, 14.124628, 14.125309, 13.817903]	[20.91298, 24.343964, 26.700623, 26.866516, 26.681625, 27.516144, 28.236954, 27.982681, 27.335419, 26.74852, 26.208313, 25.689331, 25.31456, 24.932999, 24.59488, 24.283478, 24.115417, 24.166458, 24.373703, 24.386597, 24.20082, 24.107178, 24.081741, 24.413437, 24.660263, 24.615341, 24.797943, 24.482834, 24.36473, 24.150818, 23.536407, 22.838028, 22.168549, 21.571976, 19.719315, 19.954208, 20.986832, 21.454498, 21.57872, 21.01178]
> ```
> 
> **3. when I use the latter 2849540 clips to compute CMVN. It gets:**
> 
> ```
> speaker	mean	var
> global	[10.706122, 12.945589, 13.843145, 14.105223, 14.120722, 14.203944, 14.277449, 14.322074, 14.235685, 14.069682, 14.00042, 13.92407, 13.829724, 13.73798, 13.673741, 13.572355, 13.631356, 13.762076, 13.852783, 13.806102, 13.672217, 13.506154, 13.506403, 13.557284, 13.652725, 13.762564, 13.830316, 13.939399, 13.906135, 13.835582, 13.766824, 13.514759, 13.146294, 12.073899, 10.869639, 11.802343, 13.080408, 13.547596, 13.629309, 13.576775]	[25.609474, 29.985321, 32.22003, 32.230743, 32.167343, 32.777786, 33.076553, 32.794342, 32.309784, 31.979416, 31.775513, 31.46672, 31.243546, 31.00354, 30.644836, 30.279953, 30.18895, 30.408676, 30.774078, 30.894089, 30.7453, 30.623108, 30.571, 31.106644, 31.374847, 31.314392, 31.676956, 31.279175, 31.005249, 30.59291, 29.569138, 28.275925, 26.933304, 24.142456, 17.697388, 20.731049, 24.888977, 26.118454, 26.608932, 26.611694]
> ```
> 
> In summary, the total counts of clips is 3849540, it gots negative number. Yet the either partial subset seems.
> I suspect it might be numeric overflow somewhere?
> @tjadamlee @Some-random

Thank you for spotting this out! We will check this ASAP.

**Comment by Some-random** [comment]
tf.float32 will cause overflow for huge amounts of data, but the overflow value seems to be inf... Can you please change the dtype of initial_mean and initial_var to tf.float64 and run the 3849540 clips experiment again?

**Comment by iou2much** [comment]
yes. I just got the result for tf.float64:
```csv
speaker	mean	var
global	[-11.376847856081284, -13.70883247188054, -14.667681742251705, -14.950129562794944, -14.947465430791905, -15.033160198760662, -15.12826343935544, -15.175159077952202, -15.074336066821333, -14.895296262910943, -14.828947142500907, -14.754188050800378, -14.658958534068216, -14.570596458773172, -14.51388850150753, -14.415023545081322, -14.48267495526615, -14.623471668046424, -14.718002678500538, -14.66964030917306, -14.541042130068286, -14.384992578767426, -14.399876971327018, -14.46484355865733, -14.567911645310724, -14.677954971601721, -14.749396530076673, -14.859197253177118, -14.827686975989458, -14.757664970292028, -14.682159530811814, -14.43401245454009, -14.073907988485374, -13.036204705584721, -11.871612968077022, -12.774684916782546, -14.01323382758037, -14.469095477488887, -14.536002370777007, -14.419020815375934]	[-277.7637058082368, -395.9610969818807, -451.28753826967454, -467.611134539212, -467.35760048574315, -473.0552446986533, -479.05513020657816, -481.52782520273036, -475.0415757853234, -464.19156655843994, -460.0588528625749, -455.379961688463, -449.65923461714704, -444.3484406553696, -440.76853601965155, -434.8346846714102, -438.5252146199799, -446.6902593564421, -452.43378124684455, -449.77077794106617, -442.3026011712685, -433.41016360476647, -434.20487247000636, -438.37877211287866, -444.480705395536, -450.67630665493016, -455.10618362053543, -461.0258183180864, -458.9561896816808, -454.54151853500645, -449.2307085263161, -433.96582418540436, -412.76589284020645, -355.74831989770735, -293.8303559374171, -339.48637446970906, -407.50621016173056, -433.84323850447436, -438.0329630417142, -431.2742803919692]
```

**Comment by iou2much** [comment]
Finally~Case closed . @Some-random @tjadamlee 

After I cast the total_num to int64, it gets normal result.

Turns out that in my case the total_num will be 2207758941, which is out of range of signed int32 (-2,147,483,648 ~ 2,147,483,647)

Maybe the dtype should be uint32 at least? or dynamically adapted with the data?
