### ISSUE TITLE
A bug in rnnlm.json in librispeech example

### ISSUE THREAD

**Issue by tjadamlee** [athena-team/athena#114]
"dataset_builder": "language_dataset",
  "num_data_threads": 1,
  "trainset_config":{
    "data_csv":"/nfs/cold_project/zhangruixiong/athena_librispeech/examples/asr/librispeech/data/train-speaker-id.trans.csv",
    "input_text_config":{"type":"vocab", "model":"/nfs/cold_project/zhangruixiong/athena_librispeech/examples/asr/aishell/data/vocab"},
    "output_text_config":{"type":"vocab", "model":"/nfs/cold_project/zhangruixiong/athena_librispeech/examples/asr/aishell/data/vocab"}
  },
  "devset_config":{
    "data_csv":"/nfs/cold_project/zhangruixiong/athena_librispeech/examples/asr/librispeech/data/test-clean-speaker-id.trans.csv",
    "input_text_config":{"type":"vocab", "model":"/nfs/cold_project/zhangruixiong/athena_librispeech/examples/asr/aishell/data/vocab"},
    "output_text_config":{"type":"vocab", "model":"/nfs/cold_project/zhangruixiong/athena_librispeech/examples/asr/aishell/data/vocab"}
  }
}

**Comment by tjadamlee** [comment]
@cookingbear "/nfs/cold_project/zhangruixiong/athena_librispeech/examples/asr/aishell/data/vocab"
please provide the file under the condition of the experimental environment 
@Some-random @cookingbear this should not happen again

**Comment by tjadamlee** [comment]
please finish this asap @cookingbear @Some-random

**Comment by cookingbear** [comment]
ok I will check this again
