### ISSUE TITLE
decode_main : epoch selection of highest CTCAccuracy taking in rnn epoch as well

### ISSUE THREAD

**Issue by enchyisle** [athena-team/athena#118]
https://github.com/athena-team/athena/blob/3bddf669e97b8b51db0d563d0d89e60690c55d0e/athena/decode_main.py#L43-L49

I suppose this part of code wants to take in lines like this:
INFO:absl:epoch: 24	loss: 6.2964	Accuracy: 0.9983	CTCAccuracy: 0.8945	

But it seems to be taking in epochs from rnnlm traininng as well:
INFO:absl:epoch: 0	loss: 8.5147	AverageLoss: 8.3501	

As a result, the selected epoch might be wrong.
Could someone take a look?
Thanks.

**Comment by Some-random** [comment]
Selecting epoch based on language model logs is definitely wrong. We will make a pr soon that writes the log of different training stages in separate files.
