### ISSUE TITLE
assert in solver.py and json config makes it not workable for single-GPU envrionments

### ISSUE THREAD

**Issue by enchyisle** [athena-team/athena#119]
https://github.com/athena-team/athena/blob/3bddf669e97b8b51db0d563d0d89e60690c55d0e/athena/solver.py#L54

If only one GPU is available, it's always false. 
I had to change it to >= to make it run.

https://github.com/athena-team/athena/blob/3bddf669e97b8b51db0d563d0d89e60690c55d0e/examples/asr/aishell_sub/configs/mtl_transformer_sp.json#L8

I had to change this 2 to 0, too.

**Comment by Some-random** [comment]
Thank you for spotting this out. We will make a pr to fix it.

**Comment by jinsongpan** [comment]
> Thank you for spotting this out. We will make a pr to fix it.

what does ""solver_gpu" mean? why should "assert len(gpus) > len(visible_gpu_idx)"?

**Comment by Some-random** [comment]
It means the gpu indexes used to train the model. We added this assertion to make sure number of gpus you want to use must be more than number of gpus available.
