### ISSUE TITLE
run.sh error: script will stop halfway without entering the next stage

### ISSUE THREAD

**Issue by jinsongpan** [athena-team/athena#122]
After executing each stage(since stage2), the run.sh script will stop halfway without entering the next stage. And there is no prompt in the log. logs are attached below.
[stage0&stage1.log](https://github.com/athena-team/athena/files/4464042/stage0.stage1.log)
[stage4.log](https://github.com/athena-team/athena/files/4464043/stage4.log)
[stage3.log](https://github.com/athena-team/athena/files/4464044/stage3.log)
[stage2.log](https://github.com/athena-team/athena/files/4464045/stage2.log)

**Comment by Some-random** [comment]
We have experienced similar problems when training with Horovod and we're still trying to figure out the root cause of it.

One temporary solution that works is to execute training commands inside [screen](https://www.thegeekdiary.com/how-to-use-the-screen-command-in-linux/) instead of nohup.

**Comment by jinsongpan** [comment]
> We have experienced similar problems when training with Horovod and we're still trying to figure out the root cause of it.
> 
> One temporary solution that works is to execute training commands inside [screen](https://www.thegeekdiary.com/how-to-use-the-screen-command-in-linux/) instead of nohup.


thanks for your advice. I suspected it caused by the version conflict between tf2, cudnn and CUDA. so I strictly follow tf's official recommended configuration to run the script(used: tf2.0+cuda10.0+cudnn7.6 -> now:  tf2.1+cuda10.0+cudnn7.4). if the test is finished, I'll share the result here.
