### ISSUE TITLE
Using GPU for training, and CPU for decoding, Can we?

### ISSUE THREAD

**Issue by studyself** [athena-team/athena#125]
It's very slow during decoding for AISHELL task. 
It seems that only 1 GPU is chosen to perform decoding.
However, I have got 32 CPU kernels. 
How to use CPUs for decoding and make it faster?
_______
athena/examples/asr/aishell/configs/mtl_transformer_sp.json:
  "solver_gpu":[0],
  "solver_config":{
    "clip_norm":100,
    "log_interval":10,
    "enable_tf_function":true

**Comment by iou2much** [comment]
just disable GPU when decoding like this
`        export CUDA_VISIBLE_DEVICES="-1"`
yet still..it's quite slow
