### ISSUE TITLE
no test dataset cer result

### ISSUE THREAD

**Issue by LeoMax-Xiong** [athena-team/athena#129]
https://github.com/athena-team/athena/blob/1b535ad2a5eb278dc827273958f26bbbeb73346f/athena/solver.py#L162

In the decode process,  athena print all single line cer/wer。But after decoding, it doesn't print the cer over the all dataset。
I think athena should print the dataset cer before the following line:
``` python
logging.info("decoding finished")
```
Or maybe I do not find the correct cer position in the nohup.out????

**Comment by Some-random** [comment]
The avg_acc in decoding log means the average accuracy over all test wav files decoded. So the accuracy over the whole test set is basically the last avg_acc printed by decode_main.

**Comment by Some-random** [comment]
@cookingbear please add a more explicit message for accuracy over the whole test set.

**Comment by Some-random** [comment]
Leave this issue open. We will make a pr to show CER explicitly with sclite.
