### ISSUE TITLE
more GPU error and one gpu error too

### ISSUE THREAD

**Issue by xbsdsongnan** [athena-team/athena#136]
1. 4 gpu :unknown:ncclcomminitrank failed :unhandled system error
2.1gpu :ran out of memory trying to allocate 2.57GiB

**Comment by Some-random** [comment]
Issue 1 is related to NCCL installation.
Issue 2 means batch size is too big for your GPU.

**Comment by tjadamlee** [comment]
To run on GPUs with NCCL:

$ HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_GPU_BROADCAST=NCCL pip install horovod

more information can be checked in https://github.com/horovod/horovod

**Comment by xbsdsongnan** [comment]
now,we use only one gpu for horovodrun ,horovodrun -np 1 -H localhost:2,this is ok. but we use two gpu for training, Read -1,expected 1638400,errno = 1,the training is ok too. when we use four gpu, unknown:ncclcomminitrank failed :unhandled system error.

**Comment by xbsdsongnan** [comment]
now,we use only one gpu for horovodrun ,horovodrun -np 1 -H localhost:1,this is ok. but we use two gpu for training, Read -1,expected 1638400,errno = 1,the training is ok too. when we use four gpu, unknown:ncclcomminitrank failed :unhandled system error.

**Comment by tjadamlee** [comment]
@xbsdsongnan This is related to the horovod, maybe you can check out more information from like https://github.com/horovod/horovod/issues/1195

**Comment by JianweiSun007** [comment]
@xbsdsongnanThis is a script for auto install horovod in centos and maybe help for you
https://github.com/8z8z8z/athena/blob/master/tools/build_horovod_centos_env.sh
