### ISSUE TITLE
please using logging module

### ISSUE THREAD

**Issue by LeoMax-Xiong** [athena-team/athena#140]
https://github.com/athena-team/athena/blob/c3375c09667daaad5b233cc9bc17fd1f9a840e30/athena/decode_main.py#L50

In this decode_main.py, only using logging in the line 75 and line 77, but other logging info uses the `print`。I suggest that all the logging info should using logging module and configure the logging configuration in the some *.json。

**Comment by tjadamlee** [comment]
we will update in https://github.com/athena-team/athena/pull/144
