### ISSUE TITLE
Add a markdown document for wer

### ISSUE THREAD

**Issue by tjadamlee** [athena-team/athena#141]
store in athena/doc/wer_are_we
we can reference to https://github.com/syhw/wer_are_we, but we add more information related to Mandarin Chinese corpus and github opensource results other than paper

**Comment by LeoMax-Xiong** [comment]
This benchmark will arise a more attractive thing around athena for Mandarin Chinese CORPUS

**Comment by Some-random** [comment]
@neneluo let's work together on this

**Comment by neneluo** [comment]
> @neneluo let's work together on this

Sure.
