### ISSUE TITLE
batch or iteration

### ISSUE THREAD

**Issue by LeoMax-Xiong** [athena-team/athena#145]
https://github.com/athena-team/athena/blob/6d85def4dc84aa8470e186dcb8359062a2e1e4bd/athena/solver.py#L85

When I read the script, I think the meaning of `batch` is equal to `iteration`。If it equals to `iteration`，I suggest that it can replace `batch` with `iteration`。

And when I read the mpc script, could author give the reference paper。
https://github.com/athena-team/athena/blob/6d85def4dc84aa8470e186dcb8359062a2e1e4bd/athena/models/masked_pc.py#L18

And in the following function:
https://github.com/athena-team/athena/blob/6d85def4dc84aa8470e186dcb8359062a2e1e4bd/athena/main.py#L82

the configuration has been parsed in the main.py:170。Could the parse process or the `p` around line main.py:170 be reused 。

**Comment by tjadamlee** [comment]
batch related to minibatch.
About reference paper information, we will make it more clear in the near future. 
In athena, each time, when we need the information from jsonfile, we may parse again so that we can make each function more independent against others
