### ISSUE TITLE
acc turns into zero in the middle

### ISSUE THREAD

**Issue by iou2much** [athena-team/athena#148]
![image](https://user-images.githubusercontent.com/2812471/79541271-19022780-80bc-11ea-888b-3d1d459854b6.png)

**Comment by iou2much** [comment]
again...
![image](https://user-images.githubusercontent.com/2812471/79549397-8072a400-80c9-11ea-8ee9-c6fe5d430684.png)

**Comment by Some-random** [comment]
Your learning rate is probably too high. Try to use a smaller k in optimizer_config

**Comment by iou2much** [comment]
Thank you.
