### ISSUE TITLE
redefine SpeechTransformer2

### ISSUE THREAD

**Issue by tjadamlee** [athena-team/athena#16]
@leixiaoning using the new approach to implement the SpeechTransformer2 call function, in which we forward twise: the first time forward is used to generate the predicted target, the second forward is used to intergate the ground truch, so that we can enable the schedule sampling

**Comment by Some-random** [comment]
reference: https://arxiv.org/abs/1906.07651

**Comment by tjadamlee** [comment]
@leixiaoning please finish this maybe this week

**Comment by leixiaoning** [comment]
@tjadamlee  it's done

**Comment by tjadamlee** [comment]
@leixiaoning please re-open a new PR, and then close this issue
