### ISSUE TITLE
why update  aishell‘s wer?

### ISSUE THREAD

**Issue by sigpro** [athena-team/athena#161]
Hi,I found that aishell's wer update from 5.77 to 6.6,what's the problem of  the result with 5.77.
Thanks for your work.

**Comment by Some-random** [comment]
Because we made a mistake by setting the **max_length** of AISHELL test set to 8000 (8 seconds) during decoding, but about 6% of AISHELL test set are longer than 8 seconds. Adding these back increases the overall WER.
