### ISSUE TITLE
Athena got error when training aishell dataset

### ISSUE THREAD

**Issue by leohuang2013** [athena-team/athena#164]
When I was training aishell dataset, during decode stage, I got following error
![Wechat_decode](https://user-images.githubusercontent.com/4549946/80979253-afbf3a00-8e59-11ea-9671-c1c37a738fde.jpeg)

nohup.txt shows that, it was keeping show above message for whole night, therefore it made me to force kill it.

The tensorflow-gpu version 2.1.0. The reason I used version 2.1.0 is that, version 2.0.0 didn't work for me. It shows another error as shown below,
![Wechat_undefined](https://user-images.githubusercontent.com/4549946/80981633-d0d55a00-8e5c-11ea-9a78-7813180a0b36.jpeg)

I also attached config files and run.sh I used.
[configs_run.zip](https://github.com/athena-team/athena/files/4575422/configs_run.zip)

**Comment by Some-random** [comment]
Our TF version has been bumped to 2.0.1 in this [pr](https://github.com/athena-team/athena/pull/43). Can you please try 2.0.1 and let us know if it works?

**Comment by leohuang2013** [comment]
I also tried 2.0.1, same thing here as shown below,
![Screenshot from 2020-05-06 08-01-48](https://user-images.githubusercontent.com/4549946/81024719-ea9b8f00-8ea6-11ea-80b8-91cdf25a708f.png)

**Comment by tjadamlee** [comment]
@leo1980 please post some log when you run "python setup.py bdist_wheel sdist", so we can find out where these errors come from
