### ISSUE TITLE
Add OpenMandarin Dataset

### ISSUE THREAD

**Issue by tjadamlee** [athena-team/athena#17]
@Some-random add other opensource mandarin dataset

**Comment by Some-random** [comment]
@hyx100e please look into this

**Comment by Some-random** [comment]
Add ST-CMDS and combine prepare_data.py of all OpenMandarin dataset together

**Comment by hyx100e** [comment]
> Add ST-CMDS and combine prepare_data.py of all OpenMandarin dataset together

All right, I will finish it this weekend

**Comment by tjadamlee** [comment]
@hyx100e please finish this, since this is another new week
