### ISSUE TITLE
Accelerate decoding

### ISSUE THREAD

**Issue by Some-random** [athena-team/athena#18]
Beam search with CTC joint decoding is really slow, we need to accelerate it. Two solutions on top of my head:

1  split test set into smaller pieces then divide-and-conquer with horovod
2  use tf-function compatible code to rewrite CTC joint decoding part

@cookingbear please look it this

**Comment by chenguoguo** [comment]
3. If lm is used, load lm refactor the code so that lm will be loaded for only once.

**Comment by Some-random** [comment]
@cookingbear If you have tested your implementation in decoding branch, please merge it with master. Currently the decoding speed in master branch is still really slow.

**Comment by robinn37** [comment]
When will you merge this update into master? 
Currently, in the master branch, It almost takes 5 seconds for a single utterance decoding in average.

**Comment by xinedison** [comment]
Dr, Li,
@tjadamlee  If there are several gpu on my machine, could I speed up the decoding processing by adding a MultiDeviceDecoderSolver based on DecoderSolver?
 And speed up the decode process in a data parallel Mode.

**Comment by Some-random** [comment]
This issue have been resolved by this [pr](https://github.com/athena-team/athena/pull/177/files) and this [pr](https://github.com/athena-team/athena/pull/180/files). Closing it for now.
