### ISSUE TITLE
horovod with tensorflow 2.0

### ISSUE THREAD

**Issue by ExpressGit** [athena-team/athena#204]
![ed4c0f8135a30c6c6c5bb011d9d409b](https://user-images.githubusercontent.com/11694747/87129033-42011580-c2c3-11ea-93c7-afaaa8159a6c.png)

tensorflow 2.0 alreay installed
but horovod not found tensorflow
please help me

**Comment by Some-random** [comment]
horovod.tensorflow is basically the TF API of horovod, so it belongs to package horovod. Please check your horovod installation first. We also have [recipes](https://github.com/athena-team/athena/blob/master/examples/asr/aishell_sub/run.sh) that doesn't require horovod, feel free to try that one~

**Comment by ExpressGit** [comment]
thanks , the problem has been solve.
