### ISSUE TITLE
horovod with tensorflow 2.0

### ISSUE THREAD

**Issue by ExpressGit** [athena-team/athena#205]
![ed4c0f8135a30c6c6c5bb011d9d409b](https://user-images.githubusercontent.com/11694747/87129164-7d034900-c2c3-11ea-9084-40dd0469f1ef.png)
tensorflow 2.0 alreay installed
but horovod not found tensorflow
please help me

**Comment by Some-random** [comment]
Same as [https://github.com/athena-team/athena/issues/205](url)
