### ISSUE TITLE
what does "inner_packed_states" mean in the athena-decode?

### ISSUE THREAD

**Issue by HalFTeen** [athena-team/athena#208]
I have seen the explanation: "inner states need to be record, type: tuple". Are there any other role except for recording the innner states？ Because I found it can still get the correct result without the parameter. looking forword to your reply. THX.

**Comment by Some-random** [comment]
inner_packed_states records current decoding step, which is basically the number of characters in decoding candidate sequence

**Comment by HalFTeen** [comment]
> inner_packed_states records current decoding step, which is basically the number of characters in decoding candidate sequence

Thank you very much. So, that means the parameter can be removed  if I have another parameter to judge whether decoder is end, right?

**Comment by Some-random** [comment]
Yes
