### ISSUE TITLE
decoding output

### ISSUE THREAD

**Issue by chenguoguo** [athena-team/athena#21]
We have to do couple of things regarding decoding output:

1. Add configuration to write file to disk;

2. Compare WER/CER with standard tools.

Assigning tasks to myself for now.

**Comment by Some-random** [comment]
We implemented CER/WER computation with sclite. Please help us review it at [https://github.com/athena-team/athena/pull/170](url)

**Comment by Some-random** [comment]
This issue has been addressed with [this pr](https://github.com/athena-team/athena/pull/170) and [this pr](https://github.com/athena-team/athena/pull/185). Closing this issue for now. Please reopen it if further question exists.
