### ISSUE TITLE
Efficiency of openfst-python

### ISSUE THREAD

**Issue by HalFTeen** [athena-team/athena#214]
I want to build my own LG with the scripy "pydecoders/build_graph_main.py" .  4233 Chinese character compose the graphme.txt, 123728 words compose the lexicon.txt, my arpa file is 557M. I have executed the script for 956 minutes and 116G of memory till now.    I don't kown how much longer and how much memory if run the scripy. Or am I  wrong somewhere? Are you experienced about openfst-python in time and memory using? THX.

**Comment by Some-random** [comment]
We haven't seen situations like yours before. Maybe @godjealous can help look into this?
