### ISSUE TITLE
beam search decode so slow

### ISSUE THREAD

**Issue by ExpressGit** [athena-team/athena#215]
beam search decode so slow?
how to optimizing this problem

**Comment by Some-random** [comment]
@cookingbear addressed decoding speed in previous pr. @cookingbear please help @ExpressGit with this problem

**Comment by ExpressGit** [comment]
Where did I locate the problem:
1、File: tools/beam_search.py      Funciotn: __call__  
2、Too many iterations
3、beam search score Calculate slow
![image](https://user-images.githubusercontent.com/11694747/87737900-ba5d5e80-c80e-11ea-95f3-9ccb0b5c8447.png)

**Comment by cookingbear** [comment]
Iterations are not the issue. 
Beam search may use ctc scorer and currently it will dramatically slow down the decoding speed. However, we will update this part shortly.
You can also use horovod_decode_main.py to utilize multiple gpus for decoding.

**Comment by ExpressGit** [comment]
The decode component consists of RNN Model and CTC decode.
I have removed CTC deocde,only use RNN model decode . and also  update the beam size.
Decode speeds up to four times faster.the error Rate will be higher
