### ISSUE TITLE
ModuleNotFoundError: No module named 'pydecoders'

### ISSUE THREAD

**Issue by zcy618** [athena-team/athena#218]
hi friends:
when I run below command:

python athena/main.py examples/translate/spa-eng-example/transformer.json

there is one error as below:

(athena-train-env) parallels@parallels-Parallels-Virtual-Platform:~/Desktop/asr/athena$ python athena/main.py examples/translate/spa-eng-example/transformer.json
There is some problem with your horovod installation. But it wouldn't affect single-gpu training
There is some problem with your horovod installation. But it wouldn't affect single-gpu training
Traceback (most recent call last):
File "athena/main.py", line 24, in
from athena import *
File "/home/parallels/Desktop/asr/athena/athena/init.py", line 56, in
from .solver import BaseSolver
File "/home/parallels/Desktop/asr/athena/athena/solver.py", line 34, in
from pydecoders import WFSTDecoder
ModuleNotFoundError: No module named 'pydecoders'

and I try to install pydecoders, but there is not:

(athena-train-env) parallels@parallels-Parallels-Virtual-Platform:~/Desktop/asr/athena$ pip install pydecoders
ERROR: Could not find a version that satisfies the requirement pydecoders (from versions: none)
ERROR: No matching distribution found for pydecoders

So could you tell me how should I install it please?

Thanks.

**Comment by Some-random** [comment]
You can find installation guide for pydecoder [here](https://github.com/athena-team/athena-decoder#installation). We will update this requirement in README soon.

**Comment by tjadamlee** [comment]
@Some-random we should update this "from pydecoders import WFSTDecoder " like that horovod, use "try"
