### ISSUE TITLE
x_ops.so: undefined symbol

### ISSUE THREAD

**Issue by ExpressGit** [athena-team/athena#221]
1、python3 setup.py bdist_wheel sdist  success
2、python3 -m pip install  dist/athena-0.1.0*.whl  success
3、generate x_ops.so file  success
error info:
tensorflow.python.framework.errors_impl.NotFoundError: /athena/athena/transform/feats/ops/x_ops.so: undefined symbol: _ZTIN10tensorflow8OpKernelE
![image](https://user-images.githubusercontent.com/11694747/88039321-fd566380-cb79-11ea-819e-eb934323e6d2.png)

please help me

**Comment by Some-random** [comment]
This looks like an issue with TF version. What's your TF version?

**Comment by ExpressGit** [comment]
TF version:2.0.0 
the problem has been solved
recompile the code:
1、python3 setup.py bdist_wheel sdist success
2、python3 -m pip install dist/athena-0.1.0*.whl success
