### ISSUE TITLE
python: can't open file 'CUDA_VISIBLE_DEVICES=': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by zcy618** [athena-team/athena#224]
when I run the shell:
./examples/asr/aishell/run.sh

I got an error:
INFO:absl:Finished processing AISHELL subset test
Computing cmvn
python: can't open file 'CUDA_VISIBLE_DEVICES=': [Errno 2] No such file or directory

what should I do please? Or do I miss something?
Thanks.

**Comment by Some-random** [comment]
"CUDA_VISIBLE_DEVICES=" should be placed before python. Thanks for spotting this bug out
