### ISSUE TITLE
how to understand the input and output data

### ISSUE THREAD

**Issue by zcy618** [athena-team/athena#227]
Dear friends:
Could I ask one basic question please? I notice the input shape is (4, xxx, 40, 1), the output shape is (4,), like below:
{'input': <tf.Tensor: id=72353, shape=(4, 204, 40, 1), dtype=float32,.........
'input_length': <tf.Tensor: id=72362, shape=(4,), dtype=int32, numpy=array([204, 204, 204, 204],.....

'output': <tf.Tensor: id=72356, shape=(4, 204, 40), dtype=float32,
'output_length': <tf.Tensor: id=72362, shape=(4,), dtype=int32, numpy=array([204, 204, 204, 204], dtype=int32)

So I want to know why the output shape is so, I mean, for example, Here is one wav:
aa.wav 你好
so the output should be utf-8 code of "你好", I do not understand why it is 204x40

Thanks.

**Comment by Some-random** [comment]
What's the task you're running? If it's MPC, the shape of input and output should be the same

**Comment by zcy618** [comment]
> What's the task you're running? If it's MPC, the shape of input and output should be the same

yes, it is the default of MPC, why it should be the same?
Thanks

**Comment by Some-random** [comment]
Because the target of MPC is the masked part of input speech feature, we have some logic in the code to only calculate the loss between masked input feature and output of Transformer encoder

**Comment by zcy618** [comment]
hi, interesting, do you have some paper or introduction to explain why you process it like this please? BTW, after the output, I think there should be one step to align the output and the utf-8 code(such as "你好")， could I know how you process it please?
I just new one to your anthena, sorry for simple questions.
Thanks

**Comment by Some-random** [comment]
You can checkout our paper here: https://arxiv.org/pdf/1910.09932.pdf.

To run ASR model, you can just skip step3 and run step4 of [the ASR pipeline](https://github.com/athena-team/athena/blob/master/examples/asr/README.md)
