### ISSUE TITLE
decode error

### ISSUE THREAD

**Issue by zcy618** [athena-team/athena#230]
Dear friends:
when I run aishell asr step 5:
if [ ${stage} -le 5 ] && [ ${stop_stage} -ge 5 ]; then
    # decoding stage
    echo "Running decode ..."
    python athena/decode_main.py \
        examples/asr/aishell/configs/mtl_transformer_sp.json > decode.log || exit 1
fi

I meet below error:

INFO:absl:Loading data from examples/asr/aishell/data/train.trans.csv
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 120097/120097 [00:02<00:00, 58855.69it/s]
INFO:absl:trying to restore from : examples/asr/aishell/ckpts/rnnlm
Traceback (most recent call last):
  File "athena/decode_main.py", line 63, in <module>
    decode(jsonfile)
  File "athena/decode_main.py", line 42, in decode
    solver = DecoderSolver(model, config=p.decode_config, lm_model=lm_model)
  File "/data/nfs_rt19/chenyu/athena/athena/solver.py", line 231, in __init__
    self.hparams = register_and_parse_hparams(self.default_config, config, cls=self.__class__)
  File "/data/nfs_rt19/chenyu/athena/athena/utils/hparam.py", line 694, in register_and_parse_hparams
    hparams.override_from_dict(config)
  File "/data/nfs_rt19/chenyu/athena/athena/utils/hparam.py", line 536, in override_from_dict
    self.set_hparam(name, value)
  File "/data/nfs_rt19/chenyu/athena/athena/utils/hparam.py", line 462, in set_hparam
    param_type, is_list = self._hparam_types[name]
KeyError: 'beam_search'
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.iter

could you help to check it please?
Thanks.

**Comment by Some-random** [comment]
The argument in config for beam search has been changed in a previous [pr](https://github.com/athena-team/athena/pull/201), please change **"beam_search":true** in config to **"decoder_type":"beam_search_decoder"** for now. 

We will revise these configs later when we decide how to combine wfst graph creation and wfst decoding together.
