### ISSUE TITLE
miss "," at line 48 of athena/main.py

### ISSUE THREAD

**Issue by fming** [athena-team/athena#232]

**Comment by Some-random** [comment]
Thanks for spotting this out. We've fixed it.

**Comment by Some-random** [comment]
Thanks for spotting this out. We've fixed it.

**Comment by Some-random** [comment]
Thanks for spotting this out. We've fixed it.

**Comment by Some-random** [comment]
Thanks for spotting this out. We've fixed it.

**Comment by Some-random** [comment]
Thanks for spotting this out. We've fixed it.

**Comment by Some-random** [comment]
Thanks for spotting this out. We've fixed it.

**Comment by Some-random** [comment]
Thanks for spotting this out. We've fixed it.

**Comment by Some-random** [comment]
Thanks for spotting this out. We've fixed it.

**Comment by Some-random** [comment]
Thanks for spotting this out. We've fixed it.

**Comment by Some-random** [comment]
Thanks for spotting this out. We've fixed it.

**Comment by Some-random** [comment]
Thanks for spotting this out. We've fixed it.

**Comment by Some-random** [comment]
Thanks for spotting this out. We've fixed it.

**Comment by Some-random** [comment]
Thanks for spotting this out. We've fixed it.
