### ISSUE TITLE
show killed when run the code "Test your installation"

### ISSUE THREAD

**Issue by fming** [athena-team/athena#233]
try to run this test code:

source tools/env.sh
python examples/translate/spa-eng-example/prepare_data.py examples/translate/spa-eng-example/data/train.csv
python athena/main.py examples/translate/spa-eng-example/transformer.json

it shows:
>>>>> start training in epoch 0
please be patient, enable tf.function, it takes time ...
killed

it seems it is terminated unexpectedly.

**Comment by Some-random** [comment]
This seems like an OOM problem, have you noticed your memory grow unexpectedly?

**Comment by fming** [comment]
Thanks! you're right, when I enlarge the RAM from 2 G to 4G, then it works.
