### ISSUE TITLE
'LanguageDatasetBuilder' object has no attribute 'compute_cmvn_if_necessary'

### ISSUE THREAD

**Issue by fming** [athena-team/athena#264]
Environment: 
OS: Centos 8
GPU: GTX 1660
CPU: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz

Error Information:

Try the step 3.6 "On a single cpu/gpu", it raise this error:
Traceback (most recent call last):
  File "athena/main.py", line 194, in <module>
    train(json_file, BaseSolver, 1, 0)
  File "athena/main.py", line 144, in train
    trainset_builder.compute_cmvn_if_necessary(rank == 0)
AttributeError: 'LanguageDatasetBuilder' object has no attribute 'compute_cmvn_if_necessary'

**Comment by Some-random** [comment]
Thanks for spotting this bug out! The root cause of this bug is we removed the **compute_cmvn** function in base dataset. We'll fix this bug in this [pr](https://github.com/athena-team/athena/pull/265)
