### ISSUE TITLE
num samples is empty

### ISSUE THREAD

**Issue by fming** [athena-team/athena#269]
OS: Centos 8

Run step 3.7) Test your installation (on single CPU/GPU)
it throws exception "num samples is empty" after long running! 

```
INFO:absl:global_steps: 7431	learning_rate: 2.2948e-04	loss: 87.4170	Accuracy: 0.3280	sec/iter: 2.5362
INFO:absl:>>>>> start evaluate in epoch 0
Traceback (most recent call last):
  File "athena/main.py", line 194, in <module>
    train(json_file, BaseSolver, 1, 0)
  File "athena/main.py", line 172, in train
    devset = devset_builder.as_dataset(p.batch_size, p.num_data_threads)
  File "/home/ming/athena/athena/data/datasets/base.py", line 117, in as_dataset
    return data_loader(self, batch_size, num_threads)
  File "/home/ming/athena/athena/data/datasets/base.py", line 34, in data_loader
    raise ValueError("num samples is empty")
ValueError: num samples is empty
```

**Comment by Some-random** [comment]
Please check your dev.csv again to make sure file path is correct and files fall into input_length_range.

**Comment by fming** [comment]
Thanks for your replying. 
1. first there is no dev.csv when run step 3.7, but here is a file /examples/translate/spa-eng-example/data/train.csv
`input_transcripts       output_transcripts
go .    ve .
go .    vete .
go .    vaya .
go .    vayase .
hi .    hola .
run !   corre !
run .   corred .
...
`
2. I don't understand which file do you want me to check? could you please tell me more.

Thanks for your patient.

**Comment by fming** [comment]
Meet similar problem when try asr/timit:
`INFO:absl:trying to restore from : examples/asr/timit/ckpts/mtl_transformer_ctc_sp/
Traceback (most recent call last):
  File "athena/main.py", line 194, in <module>
    train(json_file, BaseSolver, 1, 0)
  File "athena/main.py", line 131, in train
    p, model, optimizer, checkpointer = build_model_from_jsonfile(jsonfile)
  File "athena/main.py", line 119, in build_model_from_jsonfile
    dataset = dataset_builder.as_dataset(p.batch_size)
  File "/home/ming/athena/athena/data/datasets/base.py", line 117, in as_dataset
    return data_loader(self, batch_size, num_threads)
  File "/home/ming/athena/athena/data/datasets/base.py", line 34, in data_loader
    raise ValueError("num samples is empty")
ValueError: num samples is empty`

**Comment by Some-random** [comment]
I've checked our scripts for translation example again, turns out it's a bug that we didn't generate dev.csv for evaluation. Sorry for that and we will fix that problem soon. For now, you can just copy train.csv to dev.csv and it should be fine.

**Comment by Some-random** [comment]
> Meet similar problem when try asr/timit:
> `INFO:absl:trying to restore from : examples/asr/timit/ckpts/mtl_transformer_ctc_sp/ Traceback (most recent call last): File "athena/main.py", line 194, in <module> train(json_file, BaseSolver, 1, 0) File "athena/main.py", line 131, in train p, model, optimizer, checkpointer = build_model_from_jsonfile(jsonfile) File "athena/main.py", line 119, in build_model_from_jsonfile dataset = dataset_builder.as_dataset(p.batch_size) File "/home/ming/athena/athena/data/datasets/base.py", line 117, in as_dataset return data_loader(self, batch_size, num_threads) File "/home/ming/athena/athena/data/datasets/base.py", line 34, in data_loader raise ValueError("num samples is empty") ValueError: num samples is empty`

Timit shouldn't have this problem, have you downloaded Timit data as instructed in README.md? Have you successfully finished prepare_data.py and generated train.csv and dev.csv in **examples/asr/timit/data**?

**Comment by fming** [comment]
The information is not so clear at here:https://github.com/athena-team/athena/tree/master/examples/asr
After following the instructions: https://github.com/athena-team/athena
Now I can run TIMIT successfully without problem. 
Thanks!
