### ISSUE TITLE
Is there any trained model avaliable

### ISSUE THREAD

**Issue by zhaoyang9425** [athena-team/athena#277]

**Comment by Some-random** [comment]
We do have plans to release trained models. We probably can't upload models trained using company data, but model trained with open source data should be ok.

May I ask what exact models are you interested in?

**Comment by zhaoyang9425** [comment]
aishell and librispeech dataset

**Comment by Some-random** [comment]
Sure, we will begin to generate and collect trained model and will let you know when models for aishell and librispeech are available.
