### ISSUE TITLE
Question for Data Normalization

### ISSUE THREAD

**Issue by fming** [athena-team/athena#288]
At step 4.3 data normalization, its code example is like this:
`python athena/cmvn_main.py examples/asr/$dataset_name/configs/mpc.json examples/asr/$dataset_name/data/all.csv
`

I ran the timit dataset, so I check the folder "examples/asr/timit/data/", there are files "dev.csv", "train.csv", "test.csv",  but there is no "all.csv", do you mean I run that command with csv files one by one?

`python athena/cmvn_main.py examples/asr/$dataset_name/configs/mpc.json examples/asr/$dataset_name/data/dev.csv
python athena/cmvn_main.py examples/asr/$dataset_name/configs/mpc.json examples/asr/$dataset_name/data/train.csv
python athena/cmvn_main.py examples/asr/$dataset_name/configs/mpc.json examples/asr/$dataset_name/data/test.csv
`

**Comment by Some-random** [comment]
all.csv will be generated in stage 1. If train.csv, dev.csv and test.csv all there, there should be no reason why you don't have all.csv.

**Comment by fming** [comment]
@Some-random Sorry I didn't run the sh script run_101.sh, I just ran the scripts following 4.1/4.2/4.3...., That's the reason why I don't have the all.csv file.
