### ISSUE TITLE
aishell 例子推理报错

### ISSUE THREAD

**Issue by Emiyassstar** [athena-team/athena#312]
ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.ops.tensor_array_ops.TensorArray'>):
<tensorflow.python.ops.tensor_array_ops.TensorArray object at 0x7f8b53ff8e50>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "athena/inference.py", line 90, in <module>
    inference(jsonfile, rank_size=rank_size, rank=rank_index)  File "athena/inference.py", line 58, in inference
    solver.inference(dataset_builder.as_dataset(batch_size=1), rank_size=rank_size)  File "work/athena/athena/solver.py", line 274, in inference
    predictions = self.model.decode(samples, self.hparams, self.decoder)  File "/work/athena/athena/models/mtl_seq2seq.py", line 136, in decode
    history_predictions.write(0, last_predictions)  File "/work/athena/venv_athena/lib/python3.8/site-packages/tensorflow/python/util/tf_should_use.py", line 247, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
==================================

**Comment by Some-random** [comment]
We haven't met errors like this before. Can you provide us with the whole log (both training and decoding)?

**Comment by Emiyassstar** [comment]
我将athena/models/mtl_seq2seq.py 136 history_predictions.write(0, last_predictions)
改成history_predictions=history_predictions.write(0, last_predictions)可以解码了
