### ISSUE TITLE
about WFST decoder for AISHELL-1

### ISSUE THREAD

**Issue by Alex-Songs** [athena-team/athena#314]
Hello, when I use WFST for AISHELL decoding, the predicted label is one less than the real label, what is the reason for this?

such as:
predictions: tf.Tensor([[2994 717 206 1404 1487 1741 3702 77 1392 84 524]
labels: [[2995 718 207 1405 1488 1742 3703 78 1393 85 525]]

But the beam search is correct.

**Comment by Alex-Songs** [comment]
Thank you, I have solved the problem.

**Comment by DamonYangyang** [comment]
How did you solve it ,Ihave the same problem

**Comment by Some-random** [comment]
Sorry for the late reply. We have met problems like this before if we don't set the starting index of vocab to 0. @DamonYangyang can you check if your vocab for aishell is the same as [this one](https://github.com/athena-team/athena/blob/master/examples/asr/aishell/data/vocab)
