### ISSUE TITLE
integrate https://github.com/athena-team/athena-decoder

### ISSUE THREAD

**Issue by tjadamlee** [athena-team/athena#32]
start a new branch to integrate athena-decoder into athena project. @godjealous 
1) Currently, we can consider the athena-decoder as a seperate project, and install it using pip. 
2) In athena, we only use the provided interface in athena-decode.
3) Evaluate the decoder from two aspects: the speed, and the CER
In the future, we may update athena-decoder and athena simultaneously, 
@cookingbear please help hanyang to support this, Thanks.

**Comment by godjealous** [comment]
OK, I have design the interface for decoder and implement it for transformer model. please help me accomplish other models according to the interfaces @cookingbear

**Comment by tjadamlee** [comment]
please finish this in two weeks @cookingbear @godjealous
