### ISSUE TITLE
Bug: wrong vacab index for WFST decoding?

### ISSUE THREAD

**Issue by iou2much** [athena-team/athena#323]
https://github.com/athena-team/athena/blob/master/athena/models/mtl_seq2seq.py#L153

predictions = [self.vocab[prediction] - 1 for prediction in words_prediction]

Seems a bug, not suppose to minus 1 here

**Comment by Some-random** [comment]
Yeah it probably is a bug to complement the fact our previous vocab file didn't start with 0. Can you make sure removing the minus 1 here will get correct results on AISHELL and make a pr for us?

**Comment by iou2much** [comment]
Yes. I've already try to remove -1 here, and get correct result. I'll make a pr. thanks

**Comment by iou2much** [comment]
https://github.com/athena-team/athena/pull/326
