### ISSUE TITLE
what does "joint ctc decoding" mean?

### ISSUE THREAD

**Issue by HalFTeen** [athena-team/athena#327]
it means hybrid ctc/attention decoding?

**Comment by iou2much** [comment]
Hi,HalFTeen. you can check this out.

https://github.com/athena-team/athena/blob/b5a124d3d0870509f901c06af2127e10e1a620a1/athena/tools/ctc_scorer.py

**Comment by HalFTeen** [comment]
> Hi,HalFTeen. you can check this out.
> 
> https://github.com/athena-team/athena/blob/b5a124d3d0870509f901c06af2127e10e1a620a1/athena/tools/ctc_scorer.py

thank you
