### ISSUE TITLE
mtl_transformer_ctc 模型论文

### ISSUE THREAD

**Issue by chengpuking** [athena-team/athena#329]
问下 ASR模型中，模型 mtl_transformer_ctc 的实现， 有对应的论文么

**Comment by Some-random** [comment]
The paper for MTL training can be found [here](https://arxiv.org/abs/1609.06773) 
The paper for transformer based ASR can be found [here](https://arxiv.org/abs/1909.06317)
The paper for MTL decoding can be found [here](https://www.merl.com/publications/docs/TR2017-103.pdf)
