### ISSUE TITLE
where to use mpc model in asr example of aishell 

### ISSUE THREAD

**Issue by chengpuking** [athena-team/athena#330]
hello, i go through run.sh in asr example of aishell, i find the trained mpc model hasn't been used anywhere; 
I guess it's the method to use this mpc model by writing "pretrained_model": model_path in config files; but i find that pretrained_model is null in mtl_transformer_sp.json
what's wrong with me?

**Comment by Leeyouxie** [comment]
> hello, i go through run.sh in asr example of aishell, i find the trained mpc model hasn't been used anywhere;
> I guess it's the method to use this mpc model by writing "pretrained_model": model_path in config files; but i find that pretrained_model is null in mtl_transformer_sp.json
> what's wrong with me?

Sorry for the late reply. You can fine-tune ASR with MPC by adding MPC config path to "pretrained_model:"
e.g:
"pretrained_model": "examples/asr/hkust/configs/mpc.json",
