### ISSUE TITLE
运行失败

### ISSUE THREAD

**Issue by gurecn** [athena-team/athena#372]
运行时失败。
环境：Windows 11 64位系统， tensorflow：2.3.0，VS：2022，Python 3.8.15，cuda：V10.1.243，cudnn：7.6.0。
```
(TF2.3) PS C:\develop\athena> python setup.py bdist_wheel sdist
2022-12-16 18:22:22.624356: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
Traceback (most recent call last):
  File "setup.py", line 26, in <module>
    TF_LIB_INC, TF_SO_LIB = tf.sysconfig.get_link_flags()
ValueError: not enough values to unpack (expected 2, got 0)
(TF2.3) PS C:\develop\athena>
```
看错误是在`get_link_flags` 出了问题。修改代码后仍然报错。输出数据发现`get_link_flags` 返回结果为：
```
>>> import sys
>>> import tensorflow as tf
>>> print(tf.sysconfig.get_link_flags())
[]
```
是因为Windows环境的问题吗？
我是参考了文章[Conda+GPU+Thensorflow 2+Horovod+Athena语音技术开源工具-手把手安装教学](https://zhuanlan.zhihu.com/p/484110791)按照步骤进行的。
只有系统环境不同。
辛苦帮分析一下问题原因。

**Comment by JianweiSun007** [comment]
<img width="674" alt="image" src="https://user-images.githubusercontent.com/10572923/208153381-1b3f0449-8b0e-40f5-855b-02d0b3a8cf0f.png">
首先你的问题应该是环境导致的，athena目前仅尝试在linux下安装使用，windows下的编译环境跟linux差异很大，一些动态库以及涉及到的编程语法都跟linux有不一样的地方，这些目前还没有完整的尝试过。建议首次使用在linux下使用，后续可以慢慢尝试window下的编译以及使用
