### ISSUE TITLE
Example case for ASR

### ISSUE THREAD

**Issue by tjadamlee** [athena-team/athena#38]
Finish the results in HKUST, AISHELL, LIBRISPEECH, SWITHBOARD

**Comment by Some-random** [comment]
I've finished HKUST results w/o mpc.  @leixiaoning is working on Aishell and @cookingbear is working on Librispeech

**Comment by tjadamlee** [comment]
@Some-random @cookingbear  about the librispeech, we should prepare a run.sh

**Comment by Some-random** [comment]
> @Some-random @cookingbear about the librispeech, we should prepare a run.sh

We will make one
