### ISSUE TITLE
Any specific reasons to not choose PyTorch ?

### ISSUE THREAD

**Issue by csukuangfj** [athena-team/athena#56]
Why is tensorflow, instead of PyTorch, selected for this project ?

**Comment by tjadamlee** [comment]
This project mainly based on tensorflow2.0+, maybe in the future, we may also consider add pytorch as the backend

**Comment by Some-random** [comment]
Also, we're building this open source project with the goal of 'facilitating the building and deploy of industrial application' in mind. As of this moment, TF's support for industrial applications is still better than PyTorch. 

But there is no doubt these two frameworks are looking more and more similar...
