### ISSUE TITLE
Error when run in pure CPU machine

### ISSUE THREAD

**Issue by pc-seawind** [athena-team/athena#62]
Traceback (most recent call last):
  File "athena/main.py", line 171, in <module>
    BaseSolver.initialize_devices(p.solver_gpu)
  File "/media/runyu/D/works/algorithm/ASR/athena/athena/solver.py", line 54, in initialize_devices
    assert len(gpus) > len(visible_gpu_idx)
AssertionError

Error occurred on following codes:
    @staticmethod
    def initialize_devices(visible_gpu_idx=None):
        """ initialize hvd devices, should be called firstly """
        gpus = tf.config.experimental.list_physical_devices("GPU")
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
        if gpus is not None:
            assert len(gpus) > len(visible_gpu_idx)
            for idx in visible_gpu_idx:
                tf.config.experimental.set_visible_devices(gpus[idx], "GPU") 

the reason is the value of gpus is "[]" not "None" when running on pure CPU machine.
so "assert len(gpus) > len(visible_gpu_idx)" called but visible_gpu_idx is "None" and has no len() at this time.

**Comment by tjadamlee** [comment]
@Some-random please help check this

**Comment by Some-random** [comment]
> Traceback (most recent call last):
> File "athena/main.py", line 171, in
> BaseSolver.initialize_devices(p.solver_gpu)
> File "/media/runyu/D/works/algorithm/ASR/athena/athena/solver.py", line 54, in initialize_devices
> assert len(gpus) > len(visible_gpu_idx)
> AssertionError
> 
> Error occurred on following codes:
> @staticmethod
> def initialize_devices(visible_gpu_idx=None):
> """ initialize hvd devices, should be called firstly """
> gpus = tf.config.experimental.list_physical_devices("GPU")
> for gpu in gpus:
> tf.config.experimental.set_memory_growth(gpu, True)
> if gpus is not None:
> assert len(gpus) > len(visible_gpu_idx)
> for idx in visible_gpu_idx:
> tf.config.experimental.set_visible_devices(gpus[idx], "GPU")
> 
> the reason is the value of gpus is "[]" not "None" when running on pure CPU machine.
> so "assert len(gpus) > len(visible_gpu_idx)" called but visible_gpu_idx is "None" and has no len() at this time.

Thank you for spotting this bug. I've created a [pull request](https://github.com/athena-team/athena/pull/64) to fix it.

**Comment by chenguoguo** [comment]
I've merged the PR, so closing this. Please report again if you encounter other issues using Athena on CPU
