### ISSUE TITLE
horovod.tensorflow

### ISSUE THREAD

**Issue by Jobiro-Jostar** [athena-team/athena#63]
When I typed import horovod.tensorflow, it occured an error like that:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/adddisk/zhangjin/projects/horovod/horovod/tensorflow/__init__.py", line 25, in <module>
    check_extension('horovod.tensorflow', 'HOROVOD_WITH_TENSORFLOW', __file__, 'mpi_lib')
  File "/adddisk/zhangjin/projects/horovod/horovod/common/util.py", line 51, in check_extension
    'Horovod with %s=1 to debug the build error.' % (ext_name, ext_env_var))
ImportError: Extension horovod.tensorflow has not been built.  If this is not expected, reinstall Horovod with HOROVOD_WITH_TENSORFLOW=1 to debug the build error.

**Comment by chenguoguo** [comment]
@Some-random could you take a look or assign it to someone else? I didn't encounter this in my environment...

**Comment by Some-random** [comment]
> @Some-random could you take a look or assign it to someone else? I didn't encounter this in my environment...

I'm looking into this. @8z8z8z wrote most code for horovod part, can you also take a look at this?

**Comment by JianweiSun007** [comment]
@Jobiro-Jostar Hi, your environment maybe have some issues.
Maybe this can help you
https://github.com/horovod/horovod/issues/314
and you can try this command:
-------------
TensorFlow
To ensure that Horovod is built with TensorFlow support enabled:

$ HOROVOD_WITH_TENSORFLOW=1 pip install horovod[tensorflow]
or
HOROVOD_WITH_TENSORFLOW=1 [other flags you used before] pip install -v --no-cache-dir horovod
---------------
and more detail you can get form,
https://github.com/horovod/horovod/blob/master/docs/install.rst

**Comment by Jobiro-Jostar** [comment]
> ## @Jobiro-Jostar Hi, your environment maybe have some issues.
> Maybe this can help you
> [horovod/horovod#314](https://github.com/horovod/horovod/issues/314)
> and you can try this command:
> 
> TensorFlow
> To ensure that Horovod is built with TensorFlow support enabled:
> ## $ HOROVOD_WITH_TENSORFLOW=1 pip install horovod[tensorflow]
> or
> HOROVOD_WITH_TENSORFLOW=1 [other flags you used before] pip install -v --no-cache-dir horovod
> 
> and more detail you can get form,
> https://github.com/horovod/horovod/blob/master/docs/install.rst
I typed the command:HOROVOD_WITH_TENSORFLOW=1 [other flags you used before] pip install -v --no-cache-dir horovod[tensorflow] and the error was fixed, many thx to you
