### ISSUE TITLE
Problem: Ran out of memory 

### ISSUE THREAD

**Issue by xinkez** [athena-team/athena#67]
Hi all,

I used this commit b7b2d9117d3d83f5aaef27eed3fd3c950f5790f8, and trained the aishell example. The occupied memory of GPU went larger and larger with global_steps, finally it ran out of memory. 

os: ubuntu 16.04
tensorflow: 2.0.1

Thank you in advance.

**Comment by Some-random** [comment]
Our config for aishell requires ~17G of GPU memory on single card. Were you able to finish one epoch of training?

**Comment by xinkez** [comment]
@Some-random When training, I used 4 GPU cards (each with 11 GB memory). I am not able to finish one epoch.

Do you mean that I should decrease the batch size even with 4 GPU cards?

**Comment by Some-random** [comment]
Yes. Batch in config means 'batch size for each GPU card'.

**Comment by xinkez** [comment]
@Some-random Thank you. I will decrease the batch size, and try again.

Another question, I have trained the aishell example for almost 3 hours, but no ckpt model files can be found.

**Comment by Some-random** [comment]
We save checkpoint after finishing training for each epoch. And ckpt files will be saved in directories like examples/asr/aishell/ckpts/mtl_transformer_ctc. Were you able to finish one epoch in 3 hour training?

**Comment by xinkez** [comment]
@Some-random I have decreased the batch size to 16, and now one epoch is finished. Also, ckpt files are saved. Thank you.
