### ISSUE TITLE
a little bug in aishell example

### ISSUE THREAD

**Issue by Jobiro-Jostar** [athena-team/athena#70]
In the file examples/asr/aishell/local/prepare_data.py,the 47th line code:if not gfile.Exists(os.path.join(dataset_dir, subset)),I think the variable dataset_dir should be replaced to audio_dir.

**Comment by tjadamlee** [comment]
@leixiaoning please check

**Comment by leixiaoning** [comment]
> In the file examples/asr/aishell/local/prepare_data.py,the 47th line code:if not gfile.Exists(os.path.join(dataset_dir, subset)),I think the variable dataset_dir should be replaced to audio_dir.

use 'os.path.join(dataset_dir, subset)' means we must unzip the zip file under dataset_dir, because line 64 will use that dir.  but user may unzip under audio_dir directly, so, i will fix that. @tjadamlee

**Comment by Jobiro-Jostar** [comment]
> > In the file examples/asr/aishell/local/prepare_data.py,the 47th line code:if not gfile.Exists(os.path.join(dataset_dir, subset)),I think the variable dataset_dir should be replaced to audio_dir.
> 
> use 'os.path.join(dataset_dir, subset)' means we must unzip the zip file under dataset_dir, because line 64 will use that dir. but user may unzip under audio_dir directly, so, i will fix that. @tjadamlee

Yep, I see

**Comment by Some-random** [comment]
Please close this issue if your problem is solved @Jobiro-Jostar .
