### ISSUE TITLE
Error of decoding stage

### ISSUE THREAD

**Issue by xinkez** [athena-team/athena#80]
Hi,
When I was running the decoding stage, I got such error message:

<<<
Traceback (most recent call last):
  File "athena/decode_main.py", line 87, in <module>
    decode(jsonfile, n=5, log_file='nohup.out')
  File "athena/decode_main.py", line 65, in decode
    v = tf.reduce_mean(tf.concat(v,axis=0),axis=0)
  File "/8T_raid/user/venv_athena/lib/python3.5/site-packages/tensorflow_core/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/8T_raid/user/venv_athena/lib/python3.5/site-packages/tensorflow_core/python/ops/array_ops.py", line 1431, in concat
    return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
  File "/8T_raid/user/venv_athena/lib/python3.5/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 1249, in concat_v2
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: OpKernel 'ConcatV2' has constraint on attr 'T' not in 
NodeDef '[N=0, Tidx=DT_INT32]', KernelDef: 'op: "ConcatV2" device_type: "GPU" constraint { name: "T" allowed_values
{ list { type: DT_INT32 } } } host_memory_arg: "values" host_memory_arg: "axis" host_memory_arg: "output"' [Op:ConcatV2] name: concat

>>>

**Comment by Some-random** [comment]
@cookingbear please look into this

**Comment by cookingbear** [comment]
That may be caused by envs. Which version of tensorflow do you use to train and decode?
If your requirement is different from ours, please show your env list with versions.

**Comment by xinkez** [comment]
@cookingbear 

tensorflow-gpu 2.0.1
cuda 10.0.130

**Comment by Jobiro-Jostar** [comment]
> @cookingbear
> 
> tensorflow-gpu 2.0.1
> cuda 10.1

Well, tensorflow 2.0 could not be compatible with cuda 10.1, it can only support cuda 10.0.TF2.1 could support cuda 10.1

**Comment by xinkez** [comment]
@Jobiro-Jostar 
Sorry, I double check the cuda's version. It is 10.0.130.

**Comment by cookingbear** [comment]
@xinkez Well, did you save the train and evaluation log? In the current decoding mode, N-best Checkpoints were loaded and averaged which depend on the saved log named as "nohup.out" during training. 
I will add this check soon. If you did not save any log during training, you can temporarily touch a "nohup.out" file under the root directory and append a line to the file as below:

epoch: yourbestepochnum

**Comment by xinkez** [comment]
@cookingbear 
I saved the train and evaluation logs, but the name was not "nohup.out". I follow your instructions, and now it run without errors. 

Does the decoding process run with only one gpu? Now It is 6.9 sec/iter. Is it right?

**Comment by cookingbear** [comment]
> @cookingbear
> I saved the train and evaluation logs, but the name was not "nohup.out". I follow your instructions, and now it run without errors.
> 
> Does the decoding process run with only one gpu? Now It is 6.9 sec/iter. Is it right?

yes, the decoding process supports only one gpu currently. And the speed optimization and multi-gpu support will be updated soon.

**Comment by xinkez** [comment]
@cookingbear 
Thank you. I will close the issue.
