### ISSUE TITLE
an installation problem on win10

### ISSUE THREAD

**Issue by leospark** [athena-team/athena#82]
i am installing athena on my win10 system, this problem comes to me: 
![image](https://user-images.githubusercontent.com/34911790/77829076-94765600-715a-11ea-98dd-5ba12105d942.png)

I will appreciate it for any help.

**Comment by leospark** [comment]
>**python setup.py bdist_wheel sdist**
Traceback (most recent call last):
  File "setup.py", line 26, in <module>
    TF_LIB_INC, TF_SO_LIB = tf.sysconfig.get_link_flags()
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by Some-random** [comment]
Athena is mostly built on Linux and we haven't tested installation on Windows 10. Is this possible for you to use Linux on Window 10?

**Comment by leospark** [comment]
> Athena is mostly built on Linux and we haven't tested installation on Windows 10. Is this possible for you to use Linux on Window 10?

OK, i see.

**Comment by Some-random** [comment]
Please close this issue if your problem is solved @liziru

**Comment by leospark** [comment]
OK，i change my environment to centos7.
