### ISSUE TITLE
How to Transfer Learning?

### ISSUE THREAD

**Issue by iou2much** [athena-team/athena#85]
Hi, I wonder how to use a pretrained model for a new dataset? The new data is a total different one.
Am I supposed to use the MPC model? If so, do I need to recalculate cmvn for the new dataset?
Or can I skip the MPC stage,and finetune the latter model with new data?  i.e, SpeechTransformer, and RNNLM ? 
Please give me some guidance. Thanks a lot.

**Comment by Some-random** [comment]
The [README](https://github.com/athena-team/athena/tree/master/examples/asr) in Athena ASR examples explained the process clearly.

You do need to calcalate cmvn for the new dataset to remove variance in input distribution. MPC is simply a means to extract useful information in unsupervised data to improve the performance of ASR tasks. Using it or not is your choice.

**Comment by iou2much** [comment]
@Some-random Thank you for the replay. 
I read the doc before, and I thought it's for training from scratch.
I've trained a model with around 1100 hours opensource dataset, and get about 8% CER.
But the model perform badly for our own data.
So the next I want to try is to train a model with our user data, around 10000h.
I'm thinking to finetune all pretrained models( MPC, SpeechTransformer and LM ) with the larger dataset.
What do you recommend ? Thank you

**Comment by Some-random** [comment]
It depends on how similar (noise condition, sample rate, speaking style, etc) your user data is to opensource dataset. Training from scratch is normally better if the two datasets isn't similar enough.

**Comment by iou2much** [comment]
I see. Thanks a lot
