### ISSUE TITLE
'python examples/asr/aishell/local/prepare_data.py' failed

### ISSUE THREAD

**Issue by leospark** [athena-team/athena#88]
![image](https://user-images.githubusercontent.com/34911790/77930048-efd05180-72dc-11ea-8789-de6094174c5c.png)

$ python examples/asr/aishell/local/prepare_data.py 
Traceback (most recent call last):
  File "examples/asr/aishell/local/prepare_data.py", line 25, in <module>
    from athena import get_wave_file_length
  File "/workspace/users/lpp/source/athena/athena/__init__.py", line 18, in <module>
    from .data import SpeechRecognitionDatasetBuilder
  File "/workspace/users/lpp/source/athena/athena/data/__init__.py", line 18, in <module>
    from .datasets.speech_recognition import SpeechRecognitionDatasetBuilder
  File "/workspace/users/lpp/source/athena/athena/data/datasets/speech_recognition.py", line 22, in <module>
    from athena.transform import AudioFeaturizer
  File "/workspace/users/lpp/source/athena/athena/transform/__init__.py", line 16, in <module>
    from athena.transform import audio_featurizer
  File "/workspace/users/lpp/source/athena/athena/transform/audio_featurizer.py", line 19, in <module>
    from athena.transform import feats
  File "/workspace/users/lpp/source/athena/athena/transform/feats/__init__.py", line 16, in <module>
    from athena.transform.feats.read_wav import ReadWav
  File "/workspace/users/lpp/source/athena/athena/transform/feats/read_wav.py", line 21, in <module>
    from athena.transform.feats.ops import py_x_ops
  File "/workspace/users/lpp/source/athena/athena/transform/feats/ops/py_x_ops.py", line 28, in <module>
    spectrum = gen_x_ops.spectrum
AttributeError: module '5fa89fc3154996733eabb433e18fa62f' has no attribute 'spectrum'

I will appreciate it for any help.

**Comment by Some-random** [comment]
Have you completed the installation (running tools/install.sh)? Is the environment still windows 10?

**Comment by liziru** [comment]
Yes, i finished all installation instructions on  centos7,  not win10 .

**Comment by leospark** [comment]
> Have you completed the installation (running tools/install.sh)? Is the environment still windows 10?

Yes, i finished all installation instructions on centos7, not win10 .

**Comment by tjadamlee** [comment]
it seems something wrong on building the athena_transform. you can check about the installation of `python setup.py bdist_wheel sdist`, besides, after installation, make sure that `source tools/env.sh` firstly

**Comment by leospark** [comment]
> it seems something wrong on building the athena_transform. you can check about the installation of `python setup.py bdist_wheel sdist`, besides, after installation, make sure that `source tools/env.sh` firstly

I checked everything you referred ， all installation info shows no errors.  Any more advice ? Thank you very much.

**Comment by Some-random** [comment]
@aishinchi Please also take a look at this

**Comment by aishinchi** [comment]
> > it seems something wrong on building the athena_transform. you can check about the installation of `python setup.py bdist_wheel sdist`, besides, after installation, make sure that `source tools/env.sh` firstly
> 
> I checked everything you referred ， all installation info shows no errors. Any more advice ? Thank you very much.

Have you checked out the `*.so` in `build/lib*/Athena/transform/feats/ops/`?  Do you install Athena in the current directory or some other directory?  Can you find the` *.so `in the installation directory？

**Comment by leospark** [comment]
> > > it seems something wrong on building the athena_transform. you can check about the installation of `python setup.py bdist_wheel sdist`, besides, after installation, make sure that `source tools/env.sh` firstly
> > 
> > 
> > I checked everything you referred ， all installation info shows no errors. Any more advice ? Thank you very much.
> 
> Have you checked out the `*.so` in `build/lib*/Athena/transform/feats/ops/`? Do you install Athena in the current directory or some other directory? Can you find the`*.so`in the installation directory？

Actually, I found the error message '
![image](https://user-images.githubusercontent.com/34911790/78039293-874aa880-73a0-11ea-8eb8-288ff0b09c8a.png)' at first,  then I run command 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:....', then this error came. Do you have any advice?

**Comment by Some-random** [comment]
It seems like an error with your TensorFlow installation... Were you able to import TensorFlow?

**Comment by leospark** [comment]
> It seems like an error with your TensorFlow installation... Were you able to import TensorFlow?

![image](https://user-images.githubusercontent.com/34911790/78094348-f0650700-7406-11ea-86eb-0cc946459caf.png)
but what's wrong with my tf ? i did a tf test before.
