### ISSUE TITLE
incorrect lm_path in aishell example config

### ISSUE THREAD

**Issue by robinn37** [athena-team/athena#89]
lm_path in decode_config is incorrect in examples/asr/aishell/configs/mtl_transformer_sp.json.

examples/asr/aishell/rnnlm.json => examples/asr/aishell/configs/rnnlm.json

**Comment by Some-random** [comment]
Thanks for spotting this out. We will make a pr to fix it.

**Comment by Some-random** [comment]
Please close this issue if your problem is solved @huiding9
