### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by tjadamlee** [athena-team/athena#90]
Building some docker environment

**Comment by iou2much** [comment]
I'm using docker to train the model. I can create a PR with Dockerfile if you need:)

**Comment by wangkuiyi** [comment]
I agree that we add /Dockerfile which defines our development environment -- I am not talking about the deploy-time (runtime) environment here.

I suffered from the following errors when I follow the development procedure in /README.md to run `pip install -r requirement.txt`:

```
    Running setup.py install for horovod ... error
    ERROR: Command errored out with exit status 1:
     command: /private/tmp/venv_athena/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/f9/ymd5d3xs62gc7j6db4_8jdp40000gn/T/pip-install-4gw_0gzi/horovod/setup.py'"'"'; __file__='"'"'/private/var/folders/f9/ymd5d3xs62gc7j6db4_8jdp40000gn/T/pip-install-4gw_0gzi/horovod/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/f9/ymd5d3xs62gc7j6db4_8jdp40000gn/T/pip-record-vcte1unk/install-record.txt --single-version-externally-managed --compile --install-headers /private/tmp/venv_athena/include/site/python3.7/horovod
         cwd: /private/var/folders/f9/ymd5d3xs62gc7j6db4_8jdp40000gn/T/pip-install-4gw_0gzi/horovod/
```

It seems that something went wrong with the installation of horovod.  I often suffer from package installation problem, especially when I am working from China. It would be easier if I can 

```bash
docker run --rm -it -v $PWD:/work  athena/athena:dev bash
```

assuming our CI run `docker build & push` whenever new commits get merged into the master branch.

In SQLFlow repo, the `/.travis.yml` file configures that for merges into the following branches:

https://github.com/sql-machine-learning/sqlflow/blob/4c15b03b6dfa0f12638a03183c948a1560db1a81/.travis.yml#L9-L14

the CI would do the deploy stage

https://github.com/sql-machine-learning/sqlflow/blob/4c15b03b6dfa0f12638a03183c948a1560db1a81/.travis.yml#L97-L99

which calls `deploy.sh` to docker push the Docker image built for the CI to dockerhub.com.  Then, developers can run the above docker run command to start their development environment.

**Comment by wangkuiyi** [comment]
BTW, the reason I cannot install Horovod is explained in https://github.com/horovod/horovod/issues/52#issuecomment-420971603. The solution for macOS users is that I need to run 

```bash
CFLAGS=-mmacosx-version-min=10.7 pip install horovod
```

If I use Docker on macOS, I wouldn't need to manually install Horovod with the special setting of of `CFLAGS=-mmacosx-version-min=10.7`.

**Comment by tjadamlee** [comment]
@wangkuiyi thanks for you suggestion about this. 
Currently, it seems like that lots of users may suffer from the installation of horovod.
