### ISSUE TITLE
how to speed up cmvn computation 

### ISSUE THREAD

**Issue by iou2much** [athena-team/athena#95]
![image](https://user-images.githubusercontent.com/2812471/78104502-e8669080-7421-11ea-8d01-ea14a931fdcb.png)
![image](https://user-images.githubusercontent.com/2812471/78104587-ffa57e00-7421-11ea-87eb-94c94643b3a8.png)
![image](https://user-images.githubusercontent.com/2812471/78104602-0b914000-7422-11ea-8222-95f789c6350d.png)
![image](https://user-images.githubusercontent.com/2812471/78104714-38ddee00-7422-11ea-8d6e-9b2b1ed33ddd.png)

seems the cmvn computation stage is single process,  it takes days for our dataset, around 17000 hour, and mostly 60 secs per clip.

is it possible to make it run parallelly ?

**Comment by tjadamlee** [comment]
yes it is possible to make it run parrallelly. For example, for each speaker you can start a thread.

**Comment by iou2much** [comment]
Thanks for the reply. But our data won't have specific speakers..so I have to compute the global cmvn ? i.e. cannot run it parrallelly?

**Comment by Some-random** [comment]
You should compute global cmvn in your case. We don't support parallel cmvn computation at this moment, but you can always divide dataset into chunks and use multithread computation.

Feel free to implement it and make a pull request~

**Comment by iou2much** [comment]
Thanks. I'll try
