### ISSUE TITLE
assert len(gpus) > len(visible_gpu_idx)

### ISSUE THREAD

**Issue by MarkWuCL** [athena-team/athena#97]
Wed Apr  1 08:54:43 2020[0]<stderr>:name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.759
Wed Apr  1 08:54:43 2020[0]<stderr>:pciBusID: 0000:01:00.0
Wed Apr  1 08:54:43 2020[0]<stderr>:2020-04-01 08:54:43.171558: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
Wed Apr  1 08:54:43 2020[0]<stderr>:2020-04-01 08:54:43.173728: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
Wed Apr  1 08:54:43 2020[0]<stderr>:2020-04-01 08:54:43.175027: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
Wed Apr  1 08:54:43 2020[0]<stderr>:2020-04-01 08:54:43.175832: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
Wed Apr  1 08:54:43 2020[0]<stderr>:2020-04-01 08:54:43.178045: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
Wed Apr  1 08:54:43 2020[0]<stderr>:2020-04-01 08:54:43.179579: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
Wed Apr  1 08:54:43 2020[0]<stderr>:2020-04-01 08:54:43.183873: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
Wed Apr  1 08:54:43 2020[0]<stderr>:2020-04-01 08:54:43.183987: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
Wed Apr  1 08:54:43 2020[0]<stderr>:2020-04-01 08:54:43.184595: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
Wed Apr  1 08:54:43 2020[0]<stderr>:2020-04-01 08:54:43.185004: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
Wed Apr  1 08:54:43 2020[0]<stderr>:Traceback (most recent call last):
Wed Apr  1 08:54:43 2020[0]<stderr>:  File "athena/main.py", line 171, in <module>
Wed Apr  1 08:54:43 2020[0]<stderr>:    BaseSolver.initialize_devices(p.solver_gpu)
Wed Apr  1 08:54:43 2020[0]<stderr>:  File "/mnt/3T/mygits/ASR-NLP/FrameWorks/athena/athena/solver.py", line 54, in initialize_devices
Wed Apr  1 08:54:43 2020[0]<stderr>:    assert len(gpus) > len(visible_gpu_idx)
Wed Apr  1 08:54:43 2020[0]<stderr>:AssertionError
Process 0 exit with status code 1.
Traceback (most recent call last):
  File "/home/wcl/anaconda3/bin/horovodrun", line 21, in <module>
    run_commandline()
  File "/home/wcl/anaconda3/lib/python3.7/site-packages/horovod/run/run.py", line 876, in run_commandline
    _run(args)
  File "/home/wcl/anaconda3/lib/python3.7/site-packages/horovod/run/run.py", line 844, in _run
    _launch_job(args, remote_host_names, settings, common_intfs, command)
  File "/home/wcl/anaconda3/lib/python3.7/site-packages/horovod/run/run.py", line 867, in _launch_job
    gloo_run(settings, remote_host_names, common_intfs, env, driver_ip, command)
  File "/home/wcl/anaconda3/lib/python3.7/site-packages/horovod/run/gloo_run.py", line 287, in gloo_run
    _launch_jobs(settings, env, host_alloc_plan, remote_host_names, run_command)
  File "/home/wcl/anaconda3/lib/python3.7/site-packages/horovod/run/gloo_run.py", line 259, in _launch_jobs
    .format(name=name, code=exit_code))
RuntimeError: Gloo job detected that one or more processes exited with non-zero status, thus causing the job to be terminated. The first process to do so was:

I'm trying single GPU and close hvd。

**Comment by Some-random** [comment]
If you're using single GPU, please comment out horovod part in run.sh and change commands to something like 'python athena/main.py examples/asr/aishell/configs/xxx.json'

**Comment by sailorbj** [comment]
If the server has 4 gpu, and I want to use only 1. Could I use command like "CUDA_VISIBLE_DEVICES=0 python athena/main.py "?
It seems athena/solver.py gives assert ?

`    @staticmethod
    def initialize_devices(visible_gpu_idx=None):
        """ initialize hvd devices, should be called firstly """
        gpus = tf.config.experimental.list_physical_devices("GPU")
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
        if gpus is not None:
            assert len(gpus) > len(visible_gpu_idx)`
