### ISSUE TITLE
python script encoding suggestion

### ISSUE THREAD

**Issue by LeoMax-Xiong** [athena-team/athena#98]
the python script  `examples/asr/aishell/local/prepare_data.py `，
when I run in a chinese code envirionment, cannot run.
So I suggest add the following code to avoid the above problem:
``` pyhon
 #!/usr/bin/python
 # -*- coding: utf-8 -*-
```

**Comment by Some-random** [comment]
Thanks for pointing this out. We will make a pr to fix it.

**Comment by LeoMax-Xiong** [comment]
@leixiaoning `examples/asr/aishell/local/prepare_data.py` haven't update the script utf-8 coding
