### ISSUE TITLE
aishell/data_prepare.py tar -zxvf problem

### ISSUE THREAD

**Issue by LeoMax-Xiong** [athena-team/athena#99]
https://github.com/athena-team/athena/blob/debfeb7b4751b3770dc7d56ad5cad83085bfabf5/examples/asr/aishell/local/prepare_data.py#L49

I don't understand why to `tar -zxvf` the directory of `aishell_enroll`, `aishell_major` , `aishell_test`

And the function `convert_audio_and_split_transcript` does not use the parameter `output_dir`， So whether there is a bug in this script

**Comment by Some-random** [comment]
@leixiaoning take a look at this

**Comment by leixiaoning** [comment]
> https://github.com/athena-team/athena/blob/debfeb7b4751b3770dc7d56ad5cad83085bfabf5/examples/asr/aishell/local/prepare_data.py#L49
> 
> I don't understand why to `tar -zxvf` the directory of `aishell_enroll`, `aishell_major` , `aishell_test`
> 
> And the function `convert_audio_and_split_transcript` does not use the parameter `output_dir`， So whether there is a bug in this script

Thanks for questions, there are many tar.gz files in 'audio_dir' which is defined in line 42,('../../data_aishell/wav/')   'audio_dir+os.listdir(audio_dir)[i]' is just the i-th tar.gz file. 
and the parameter output_dir will be delected. @Honei

**Comment by LeoMax-Xiong** [comment]
> > https://github.com/athena-team/athena/blob/debfeb7b4751b3770dc7d56ad5cad83085bfabf5/examples/asr/aishell/local/prepare_data.py#L49
> > 
> > I don't understand why to `tar -zxvf` the directory of `aishell_enroll`, `aishell_major` , `aishell_test`
> > And the function `convert_audio_and_split_transcript` does not use the parameter `output_dir`， So whether there is a bug in this script
> 
> Thanks for questions, there are many tar.gz files in 'audio_dir' which is defined in line 42,('../../data_aishell/wav/') 'audio_dir+os.listdir(audio_dir)[i]' is just the i-th tar.gz file.
> and the parameter output_dir will be delected. @Honei

Thanks for reply。I download the aishell in two different time point. The first is about 2019.5, and the directory of dataset is, there is no train, dev, test directory :
``` shell
data_aishell
----wav
    -------aishell_enroll
    -------aishell_major
    -------aishell_test
----transcript
```
and the second time point is 2020.04.02， the directory of aishell is, and there is also no train, dev, test directory:
``` shell
data_aishell
----wav
    -----xxxx.tgz
----transcript
```
so I want know the md5 of your aishell dataset package.
Maybe the package of aishell have changed, so if the we download the aishell dataset package, we may not get the experiment result. @leixiaoning

**Comment by leixiaoning** [comment]
> > > https://github.com/athena-team/athena/blob/debfeb7b4751b3770dc7d56ad5cad83085bfabf5/examples/asr/aishell/local/prepare_data.py#L49
> > > 
> > > I don't understand why to `tar -zxvf` the directory of `aishell_enroll`, `aishell_major` , `aishell_test`
> > > And the function `convert_audio_and_split_transcript` does not use the parameter `output_dir`， So whether there is a bug in this script
> > 
> > 
> > Thanks for questions, there are many tar.gz files in 'audio_dir' which is defined in line 42,('../../data_aishell/wav/') 'audio_dir+os.listdir(audio_dir)[i]' is just the i-th tar.gz file.
> > and the parameter output_dir will be delected. @Honei
> 
> Thanks for reply。I download the aishell in two different time point. The first is about 2019.5, and the directory of dataset is, there is no train, dev, test directory :
> 
> ```shell
> data_aishell
> ----wav
>     -------aishell_enroll
>     -------aishell_major
>     -------aishell_test
> ----transcript
> ```
> 
> and the second time point is 2020.04.02， the directory of aishell is, and there is also no train, dev, test directory:
> 
> ```shell
> data_aishell
> ----wav
>     -----xxxx.tgz
> ----transcript
> ```
> 
> so I want know the md5 of your aishell dataset package.
> Maybe the package of aishell have changed, so if the we download the aishell dataset package, we may not get the experiment result. @leixiaoning

you should download the latter,  train,dev and test directory will appear after you unzip all files in 'data_aishell/wav/'

**Comment by leixiaoning** [comment]
> > > https://github.com/athena-team/athena/blob/debfeb7b4751b3770dc7d56ad5cad83085bfabf5/examples/asr/aishell/local/prepare_data.py#L49
> > > 
> > > I don't understand why to `tar -zxvf` the directory of `aishell_enroll`, `aishell_major` , `aishell_test`
> > > And the function `convert_audio_and_split_transcript` does not use the parameter `output_dir`， So whether there is a bug in this script
> > 
> > 
> > Thanks for questions, there are many tar.gz files in 'audio_dir' which is defined in line 42,('../../data_aishell/wav/') 'audio_dir+os.listdir(audio_dir)[i]' is just the i-th tar.gz file.
> > and the parameter output_dir will be delected. @Honei
> 
> Thanks for reply。I download the aishell in two different time point. The first is about 2019.5, and the directory of dataset is, there is no train, dev, test directory :
> 
> ```shell
> data_aishell
> ----wav
>     -------aishell_enroll
>     -------aishell_major
>     -------aishell_test
> ----transcript
> ```
> 
> and the second time point is 2020.04.02， the directory of aishell is, and there is also no train, dev, test directory:
> 
> ```shell
> data_aishell
> ----wav
>     -----xxxx.tgz
> ----transcript
> ```
> 
> so I want know the md5 of your aishell dataset package.
> Maybe the package of aishell have changed, so if the we download the aishell dataset package, we may not get the experiment result. @leixiaoning

you should download the latter, train,dev and test directory will appear after you unzip all files in 'data_aishell/wav/' @Honei

**Comment by LeoMax-Xiong** [comment]
@leixiaoning Thank you. As you answer, the train directory will appear when I unzip the wav/xxxx.tag.gz package。
